# GitLab Tree
GET https://git.nju.edu.cn/api/v4/projects/2047/repository/tree?per_page=1000&ref=master&path=.


# GitLab Raw File
###
GET https://git.nju.edu.cn/api/v4/projects/2047/repository/tree?per_page=1000&path=数学分析&ref=master


# GitHub Tree
###
GET https://api.github.com/repos/OrangeX4/NJUAI-Notes/contents/.


# GitHub Tree
###
GET https://api.github.com/repos/OrangeX4/NJUAI-Notes/contents/


# GitHub Raw File
###
GET https://raw.githubusercontent.com/OrangeX4/NJUAI-Notes/master/Test/MPE.md